version: '3.9'

services:
  rsi:
    build:
      context: .
      args:
        - IMAGE=${IMAGE}
        - BLAS=${BLAS:-liblapack-dev}
    image: rsi
    container_name: rsi
    network_mode: host
    userns_mode: host
    volumes:
      - ${PREFIX:-/opt/local}${SUBDIR}:${PREFIX:-/opt/local}${SUBDIR}
      - /etc:/tmp/etc
    environment:
      - R_VERSION=${R_VERSION}
      - CONFIG_ARGS=${CONFIG_ARGS}
      - PREFIX=${PREFIX}${SUBDIR}
      - MODE=${MODE:-install}
